INSERT INTO companies (company_id, name) VALUES ('INE404A01024', 'Aditya Birla Sun Life AMC Limited');
INSERT INTO companies (company_id, name) VALUES ('INE204E01012', 'Agarwal Industrial Corporation Limited');
INSERT INTO companies (company_id, name) VALUES ('INE298G01027', 'Ajmera Realty & Infra India Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0R4701017', 'Alpex Solar Limited');
INSERT INTO companies (company_id, name) VALUES ('INE371P01015', 'Amber Enterprises India Limited');
INSERT INTO companies (company_id, name) VALUES ('INE079A01024', 'Ambuja Cements Limited');
INSERT INTO companies (company_id, name) VALUES ('INE988S01028', 'Apeejay Surrendra Park Hotels Limited');
INSERT INTO companies (company_id, name) VALUES ('INE025R01021', 'Artemis Medicare Services Limited');
INSERT INTO companies (company_id, name) VALUES ('INE100A01010', 'Atul Limited');
INSERT INTO companies (company_id, name) VALUES ('INE118A01012', 'Bajaj Holdings & Investment Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0KQN01018', 'Bajel Projects Limited');
INSERT INTO companies (company_id, name) VALUES ('INE00E101023', 'Bikaji Foods International Limited');
INSERT INTO companies (company_id, name) VALUES ('INE439N01031', 'Blue Pearl Agriventures Limited');
INSERT INTO companies (company_id, name) VALUES ('INE032A01023', 'Bombay Dyeing & Mfg Company Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0BV301023', 'C.E. Info Systems Limited');
INSERT INTO companies (company_id, name) VALUES ('INE264T01014', 'Capacite Infraprojects Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0Z8Z23013', 'Capital Infra Trust');
INSERT INTO companies (company_id, name) VALUES ('INE0V7W01012', 'Carraro India Limited');
INSERT INTO companies (company_id, name) VALUES ('INE320B01020', 'Centum Electronics Limited');
INSERT INTO companies (company_id, name) VALUES ('INE486A01021', 'CESC Limited');
INSERT INTO companies (company_id, name) VALUES ('INE501A01019', 'Deepak Fertilizers and Petrochemicals Corporation Limited');
INSERT INTO companies (company_id, name) VALUES ('INE989C01038', 'Diamond Power Infrastructure Limited');
INSERT INTO companies (company_id, name) VALUES ('INE131C01011', 'Disa India');
INSERT INTO companies (company_id, name) VALUES ('INE385W01011', 'Dishman Carbogen Amcis Limited');
INSERT INTO companies (company_id, name) VALUES ('INE886D01026', 'EFC');
INSERT INTO companies (company_id, name) VALUES ('INE128A01029', 'Eveready Industries India Limited');
INSERT INTO companies (company_id, name) VALUES ('INE183A01024', 'Finolex Industries Limited');
INSERT INTO companies (company_id, name) VALUES ('INE291A01017', 'Garware Hi-Tech Films Limited');
INSERT INTO companies (company_id, name) VALUES ('INE025B01025', 'Goldiam International Limited');
INSERT INTO companies (company_id, name) VALUES ('INE036B01030', 'Gujarat Ambuja Exports Limited');
INSERT INTO companies (company_id, name) VALUES ('INE473B01035', 'Hatsun Agro Product Limited');
INSERT INTO companies (company_id, name) VALUES ('INE040A01034', 'HDFC Bank Limited');
INSERT INTO companies (company_id, name) VALUES ('INE835D01023', 'Hind Rectifiers Limited');
INSERT INTO companies (company_id, name) VALUES ('INE07Y701011', 'Hitachi Energy India Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0J5401028', 'Honasa Consumer Limited');
INSERT INTO companies (company_id, name) VALUES ('INE172N01012', 'Imagicaaworld Entertainment Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0D6701023', 'India Pesticides Limited');
INSERT INTO companies (company_id, name) VALUES ('INE562A01011', 'Indian Bank');
INSERT INTO companies (company_id, name) VALUES ('INE323C01030', 'Indian Hume Pipe Company Limited');
INSERT INTO companies (company_id, name) VALUES ('INE873D01024', 'Indoco Remedies Limited');
INSERT INTO companies (company_id, name) VALUES ('INE009A01021', 'Infosys Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0FLR01028', 'Inox Wind Energy Limited');
INSERT INTO companies (company_id, name) VALUES ('INE039O01029', 'Jash Engineering Limited');
INSERT INTO companies (company_id, name) VALUES ('INE573A01042', 'JK Tyre & Industries Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0OAF01028', 'JNK India Limited');
INSERT INTO companies (company_id, name) VALUES ('INE907A01026', 'Kalyani Steels Limited');
INSERT INTO companies (company_id, name) VALUES ('INE805C01028', 'KCP Limited');
INSERT INTO companies (company_id, name) VALUES ('INE602G01020', 'Kitex Garments Limited');
INSERT INTO companies (company_id, name) VALUES ('INE094I01018', 'Kolte - Patil Developers Limited');
INSERT INTO companies (company_id, name) VALUES ('INE766P01016', 'Mahindra Logistics Limited');
INSERT INTO companies (company_id, name) VALUES ('INE993A01026', 'Man Industries (India) Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0CT101020', 'Meghmani Organics Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0FRK01020', 'Motisons Jewellers Limited');
INSERT INTO companies (company_id, name) VALUES ('INE08KJ01020', 'Mufin Green Finance Limited');
INSERT INTO companies (company_id, name) VALUES ('INE800H01010', 'Omaxe Limited');
INSERT INTO companies (company_id, name) VALUES ('INE350C01017', 'Optiemus Infracom Limited');
INSERT INTO companies (company_id, name) VALUES ('INE417T01026', 'PB Fintech Limited');
INSERT INTO companies (company_id, name) VALUES ('INE063E01053', 'Pondy Oxides & Chemicals Limited');
INSERT INTO companies (company_id, name) VALUES ('INE179A01014', 'Procter & Gamble Hygiene and Health Care Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0LRY01011', 'Quadrant Future Tek Limited');
INSERT INTO companies (company_id, name) VALUES ('INE411H01032', 'R Systems International Limited');
INSERT INTO companies (company_id, name) VALUES ('INE206N01018', 'Ravindra Energy Limited');
INSERT INTO companies (company_id, name) VALUES ('INE425Y01011', 'RPSG VENTURES LIMITED');
INSERT INTO companies (company_id, name) VALUES ('INE667G01023', 'Saksoft Limited');
INSERT INTO companies (company_id, name) VALUES ('INE497B01018', 'Seamec Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0RB801010', 'Senores Pharmaceuticals Limited');
INSERT INTO companies (company_id, name) VALUES ('INE782X01033', 'Servotech Renewable Power System Limited');
INSERT INTO companies (company_id, name) VALUES ('INE932X01026', 'Share India Securities Ltd.');
INSERT INTO companies (company_id, name) VALUES ('INE386D01027', 'Shivalik Bimetal Controls Limited');
INSERT INTO companies (company_id, name) VALUES ('INE526E01018', 'Shriram Pistons & Rings Limited');
INSERT INTO companies (company_id, name) VALUES ('INE269A01021', 'Sonata Software Limited');
INSERT INTO companies (company_id, name) VALUES ('INE01EO01010', 'Spectrum Electrical Industries Limited');
INSERT INTO companies (company_id, name) VALUES ('INE937A01023', 'SPML Infra Limited');
INSERT INTO companies (company_id, name) VALUES ('INE01A001028', 'Stanley Lifestyles Limited');
INSERT INTO companies (company_id, name) VALUES ('INE239C01020', 'Stylam Industries Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0Q3R01026', 'Sundaram Clayton Limited');
INSERT INTO companies (company_id, name) VALUES ('INE00H001014', 'Swiggy Limited');
INSERT INTO companies (company_id, name) VALUES ('INE668A01016', 'Tamilnad Mercantile Bank Limited');
INSERT INTO companies (company_id, name) VALUES ('INE483C01032', 'Tanla Platforms Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0GK401011', 'Tatva Chintan Pharma Chem Limited');
INSERT INTO companies (company_id, name) VALUES ('INE011K01018', 'Tega Industries Limited');
INSERT INTO companies (company_id, name) VALUES ('INE121N01019', 'Thejo Engineering Limited');
INSERT INTO companies (company_id, name) VALUES ('INE338A01024', 'Thirumalai Chemicals Limited');
INSERT INTO companies (company_id, name) VALUES ('INE332A01027', 'Thomas Cook  (India)  Limited');
INSERT INTO companies (company_id, name) VALUES ('INE064A01026', 'Timex Group India Limited');
INSERT INTO companies (company_id, name) VALUES ('INE716B01029', 'Tips Music Limited');
INSERT INTO companies (company_id, name) VALUES ('INE454P01035', 'Transrail Lighting Limited');
INSERT INTO companies (company_id, name) VALUES ('INE064C01022', 'Trident Limited');
INSERT INTO companies (company_id, name) VALUES ('INE256C01024', 'Triveni Engineering & Industries Limited');
INSERT INTO companies (company_id, name) VALUES ('INE910C01018', 'TTK Healthcare Limited');
INSERT INTO companies (company_id, name) VALUES ('INE421C01016', 'TVS Srichakra Limited');
INSERT INTO companies (company_id, name) VALUES ('INE583D01011', 'Ugro Capital Limited');
INSERT INTO companies (company_id, name) VALUES ('INE899L01030', 'Ujaas Energy Limited');
INSERT INTO companies (company_id, name) VALUES ('INE694A01020', 'Unitech Limited');
INSERT INTO companies (company_id, name) VALUES ('INE851I01011', 'Updater Services Limited');
INSERT INTO companies (company_id, name) VALUES ('INE0AZY01017', 'Vilas Transcore Limited');
INSERT INTO companies (company_id, name) VALUES ('INE410B01037', 'Vinati Organics Limited');
INSERT INTO companies (company_id, name) VALUES ('INE669E01016', 'Vodafone Idea Limited');
INSERT INTO companies (company_id, name) VALUES ('INE251B01027', 'Zen Technologies Limited');
INSERT INTO companies (company_id, name) VALUES ('INE520A01027', 'Zensar Technologies Limited');