```
INSERT INTO financial_metrics (metric_id, name) VALUES (31, 'Altman Z-Score');
INSERT INTO financial_metrics (metric_id, name) VALUES (34, 'Asset Turnover Ratio (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (1, 'Basic EPS (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (4, 'Book Value/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (64, 'Capex/Sales (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (52, 'Capital Employed/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (40, 'Cash Conversion Cycle (CCC)');
INSERT INTO financial_metrics (metric_id, name) VALUES (3, 'Cash EPS (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (32, 'Cash Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (23, 'Current Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (39, 'Days Inventory Outstanding (DIO)');
INSERT INTO financial_metrics (metric_id, name) VALUES (38, 'Days Payable Outstanding (DPO)');
INSERT INTO financial_metrics (metric_id, name) VALUES (37, 'Days Sales Outstanding (DSO)');
INSERT INTO financial_metrics (metric_id, name) VALUES (25, 'Debt Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (65, 'Depreciation/Fixed Assets (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (2, 'Diluted EPS (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (57, 'Dividend Payout Ratio (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (58, 'Dividend Yield (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (5, 'Dividend/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (55, 'EBIT Growth (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (20, 'EBIT Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (56, 'EBITDA Growth (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (21, 'EBITDA Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (12, 'Effective tax rate (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (41, 'Fixed Asset Turnover Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (63, 'Free Cash Flow/Net Income');
INSERT INTO financial_metrics (metric_id, name) VALUES (11, 'Gross profit margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (29, 'Interest Coverage Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (35, 'Inventory Turnover Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (26, 'Long-term Debt/Equity (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (51, 'Net Asset Value (NAV)/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (28, 'Net Debt/Equity (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (54, 'Net Income Growth (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (18, 'Net Profit Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (10, 'Net Profit/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (62, 'Operating Cash Flow/EBITDA');
INSERT INTO financial_metrics (metric_id, name) VALUES (33, 'Operating Leverage Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (19, 'Operating Profit Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (48, 'P/FCF Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (49, 'P/OCF Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (47, 'P/TBV Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (46, 'PB Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (15, 'PBDIT Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (7, 'PBDIT/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (16, 'PBIT Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (8, 'PBIT/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (17, 'PBT Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (9, 'PBT/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (44, 'PE Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (45, 'PS Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (24, 'Quick Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (36, 'Receivables Turnover Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (14, 'Retention ratio (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (61, 'Return on Assets (ROA) (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (60, 'Return on Capital Employed (ROCE) (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (59, 'Return on Equity (ROE) (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (13, 'Return on insvertment (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (6, 'Revenue from Operations/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (53, 'Revenue Growth (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (43, 'Revenue/Employee (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (30, 'Shareholder Equity Ratio (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (27, 'Short-term Debt/Equity (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (50, 'Tangible Book Value/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (22, 'Total Debt/Equity (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (42, 'Working Capital Turnover Ratio (x)');
```
