INSERT INTO financial_metrics (metric_id, name) VALUES (1, 'Altman Z-Score');
INSERT INTO financial_metrics (metric_id, name) VALUES (2, 'angible Book Value/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (3, 'Asset Turnover Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (4, 'Asset Turnover Ratio (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (5, 'Basic EPS');
INSERT INTO financial_metrics (metric_id, name) VALUES (6, 'Basic EPS (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (7, 'Book Value/ Share');
INSERT INTO financial_metrics (metric_id, name) VALUES (8, 'Capex/Sales (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (9, 'Capital Employed/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (10, 'Capital Expenditure Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (11, 'Cash Conversion Cycle (CCC)');
INSERT INTO financial_metrics (metric_id, name) VALUES (12, 'Cash EPS (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (13, 'Cash Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (14, 'Current Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (15, 'Days Inventory');
INSERT INTO financial_metrics (metric_id, name) VALUES (16, 'Days Inventory Outstanding (DIO)');
INSERT INTO financial_metrics (metric_id, name) VALUES (17, 'Days Payable Outstanding (DPO)');
INSERT INTO financial_metrics (metric_id, name) VALUES (18, 'Days Sales Outstanding');
INSERT INTO financial_metrics (metric_id, name) VALUES (19, 'Debt Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (20, 'Debt to Equity Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (21, 'Depreciation/Fixed Assets (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (22, 'Diluted EPS (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (23, 'Dividend Growth');
INSERT INTO financial_metrics (metric_id, name) VALUES (24, 'Dividend Payout Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (25, 'Dividend Payout Ratio (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (26, 'Dividend Yield');
INSERT INTO financial_metrics (metric_id, name) VALUES (27, 'Dividend/ Share');
INSERT INTO financial_metrics (metric_id, name) VALUES (28, 'Earnings Yield (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (29, 'EBIT Growth');
INSERT INTO financial_metrics (metric_id, name) VALUES (30, 'EBIT Margin');
INSERT INTO financial_metrics (metric_id, name) VALUES (31, 'EBITDA Growth (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (32, 'EBITDA Margin');
INSERT INTO financial_metrics (metric_id, name) VALUES (33, 'Economic Value Added (EVA) (₹ crs)');
INSERT INTO financial_metrics (metric_id, name) VALUES (34, 'Effective tax rate');
INSERT INTO financial_metrics (metric_id, name) VALUES (35, 'Effective Tax Rate (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (36, 'Enterprise Value (₹ crs)');
INSERT INTO financial_metrics (metric_id, name) VALUES (37, 'Enterprise Value (₹ Millions)');
INSERT INTO financial_metrics (metric_id, name) VALUES (38, 'Enterprise Value to EBITDA (EV/EBITDA)');
INSERT INTO financial_metrics (metric_id, name) VALUES (39, 'Enterprise Value to Revenue (EV/Rev)');
INSERT INTO financial_metrics (metric_id, name) VALUES (40, 'Equity Turnover Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (41, 'EV/EBITDA');
INSERT INTO financial_metrics (metric_id, name) VALUES (42, 'EV/EBITDA (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (43, 'EV/Net Operating Revenue (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (44, 'Fixed Asset Turnover Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (45, 'Fixed Asset Turnover Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (46, 'Free Cash Flow Yield (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (47, 'Free Cash Flow/Net Income');
INSERT INTO financial_metrics (metric_id, name) VALUES (48, 'Gross Profit Margin');
INSERT INTO financial_metrics (metric_id, name) VALUES (49, 'Gross profit margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (50, 'Interest Burden Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (51, 'Interest Coverage Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (52, 'Interest Coverage Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (53, 'Inventory Turnover');
INSERT INTO financial_metrics (metric_id, name) VALUES (54, 'Inventory Turnover Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (55, 'Last Close Price (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (56, 'Long-term Debt/Equity (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (57, 'Long-term Debt/Equity Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (58, 'Market Cap Growth (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (59, 'Market Cap to Net Operating Revenue');
INSERT INTO financial_metrics (metric_id, name) VALUES (60, 'Market Capitalization (₹ Millions)');
INSERT INTO financial_metrics (metric_id, name) VALUES (61, 'Net Asset Value (NAV)/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (62, 'Net Debt/Equity (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (63, 'Net Debt/Equity Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (64, 'Net Income Growth (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (65, 'Net Profit Growth');
INSERT INTO financial_metrics (metric_id, name) VALUES (66, 'Net Profit Margin');
INSERT INTO financial_metrics (metric_id, name) VALUES (67, 'Net Profit/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (68, 'Operating Cash Flow Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (69, 'Operating Cash Flow/EBITDA');
INSERT INTO financial_metrics (metric_id, name) VALUES (70, 'Operating Leverage Ratio (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (71, 'Operating Profit Margin');
INSERT INTO financial_metrics (metric_id, name) VALUES (72, 'Operating Profit Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (73, 'P/FCF Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (74, 'P/OCF Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (75, 'P/TBV Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (76, 'Payables Turnover Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (77, 'PB Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (78, 'PBDIT Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (79, 'PBDIT/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (80, 'PBIT Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (81, 'PBIT/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (82, 'PBT Margin (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (83, 'PBT/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (84, 'PE Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (85, 'Price to Book Ratio (P/B)');
INSERT INTO financial_metrics (metric_id, name) VALUES (86, 'Price to Earnings Ratio (P/E)');
INSERT INTO financial_metrics (metric_id, name) VALUES (87, 'Price to Sales Ratio (P/S)');
INSERT INTO financial_metrics (metric_id, name) VALUES (88, 'PS Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (89, 'Quick Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (90, 'R&D Expense/Sales (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (91, 'Receivables Turnover');
INSERT INTO financial_metrics (metric_id, name) VALUES (92, 'Research & Development Expense/Sales (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (93, 'Retention rate');
INSERT INTO financial_metrics (metric_id, name) VALUES (94, 'Retention ratio (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (95, 'Return on Assets (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (96, 'Return on Assets (ROA) (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (97, 'Return on Capital Employed');
INSERT INTO financial_metrics (metric_id, name) VALUES (98, 'Return on Capital Employed (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (99, 'Return on Capital Employed (ROCE) (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (100, 'Return on Equity');
INSERT INTO financial_metrics (metric_id, name) VALUES (101, 'Return on Equity (ROE) (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (102, 'Return on insvertment (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (103, 'Return on inverstment (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (104, 'Return on Invested Capital (ROIC) (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (105, 'Return on investment (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (106, 'Return on Net Worth/Equity (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (107, 'Return on Total Assets (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (108, 'Return on Working Capital (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (109, 'Revenue from Operations/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (110, 'Revenue Growth');
INSERT INTO financial_metrics (metric_id, name) VALUES (111, 'Revenue/Employee (₹ in lakhs)');
INSERT INTO financial_metrics (metric_id, name) VALUES (112, 'Revenue/Employee (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (113, 'Selling, General & Admin Expense/Sales (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (114, 'SG&A Expense/Sales (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (115, 'Shareholder Equity Ratio (%)');
INSERT INTO financial_metrics (metric_id, name) VALUES (116, 'Short-term Debt/Equity (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (117, 'Tangible Book Value/Share (₹)');
INSERT INTO financial_metrics (metric_id, name) VALUES (118, 'Tax Burden Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (119, 'Total Debt/Equity (x)');
INSERT INTO financial_metrics (metric_id, name) VALUES (120, 'Working Capital Turnover Ratio');
INSERT INTO financial_metrics (metric_id, name) VALUES (121, 'Working Capital Turnover Ratio (x)');
